name: Nukeeper Update

on:
  schedule:
    - cron: '*/5 * * * *'

defaults:
  run:
    shell: pwsh
jobs:
  nukeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Nukeeper
        id: nukeeper
        uses: nukeeperdotnet/nukeeper-action@0.1
        with:
          token: '${{ secrets.RSG_PACKAGES_TOKEN }}'
